### ISSUE TITLE
After the latest update spaces are removed from {posttitle}. Previously they were replaced with hyphens

### ISSUE THREAD

**Issue by vladoa** [pablo-sg-pacheco/file-renaming-on-upload#5]
Hi Pablo! 
I really like your plugin - but since the last update 8 days ago, I noticed that the ` {posttitle}` pattern started giving results like:

`mylovelypicture.jpg`

Previously it would give result like:

`my-lovely-picture.jpg`

I suspect that this is is the [commit](https://github.com/pablo-sg-pacheco/file-renaming-on-upload/commit/6a3fb5dd83d5333d8ab6a957f62b3d9ba36a6dd0#diff-cc0a1b44f1f1ba5a7ad6710824bc25ee) that started causing the issue

Can you double check if you can reproduce this issue?

Further details:

Wordpress Version: 5.3
Plugin Version: 2.3.7

**Comment by vladoa** [comment]
I think that the regular expression should be:

`$new_post_name = preg_replace( "/[^a-zA-Z0-9-_ .]/", "", $new_post_name );`

instead of:

`$new_post_name = preg_replace( "/[^a-zA-Z0-9-_.]/", "", $new_post_name );`

I think allowing the whitespace in the regular experssion in `classes/WordPress/class-post.php:39` should fix it

**Comment by pablo-sg-pacheco** [comment]
Hi @vladoa ,
Thanks for letting me know.

I've just updated to version 2.3.8 with a fix for it.
I ended up using a solution almost like yours. Please, see https://github.com/pablo-sg-pacheco/file-renaming-on-upload/commit/f90ea0a339924e1f6d1012922e18a254a0e61b43

**Comment by vladoa** [comment]
Thanks Pablo for the fast response! I will update the plugin now.

**Comment by pablo-sg-pacheco** [comment]
;)
